# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Actividad_2Login' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Actividad_2Login
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

  target 'Actividad_2LoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Actividad_2LoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
