# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Actividad_1Login' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Actividad_1Login
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'

  target 'Actividad_1LoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Actividad_1LoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
